<a href="https://colab.research.google.com/github/pearlinoyster123-jpg/Logistic-Regression/blob/main/Logistregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('/content/drive/MyDrive/Heart disease1.csv')
df

,Age,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,ST depression,Slope of ST,Number of vessels fluro,Thallium,Exercise angina
0,58,3,120,288,0,2,145,0.8,2,3,3,1
1,55,2,120,209,0,0,172,0.0,1,0,3,0
2,54,4,120,268,0,0,150,0.0,2,3,7,1
3,44,3,112,177,0,0,168,0.9,1,0,3,0
4,43,1,138,267,0,0,163,1.8,2,0,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...
269995,58,2,120,222,0,0,172,1.0,1,0,7,0
269996,58,4,132,289,0,0,172,2.8,2,0,3,0
269997,63,3,108,201,1,0,158,0.8,1,0,3,0
269998,59,4,120,274,0,2,163,0.5,1,0,3,0
269999,42,2,120,275,0,0,173,0.0,1,1,3,0

In [5]:
df.isnull().sum()

Age                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Exercise angina            0
dtype: int64

In [6]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(df[['Age','Chest pain type','BP','Cholesterol','FBS over 120',
           'EKG results','Max HR','ST depression','Slope of ST',
           'Number of vessels fluro','Thallium']],df['Exercise angina'
      ])

LogisticRegression(max_iter=1000)

In [ ]:
lr.predict([[30,2,70,125,0,1,65,0.2,1,0,3]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
lr.score(df[['Age','Chest pain type','BP','Cholesterol','FBS over 120','EKG results','Max HR','ST depression','Slope of ST','Number of vessels fluro','Thallium']],df['Exercise angina'])

0.7587407407407407

In [ ]:
lr.coef_

array([[ 1.07973614e-02,  3.53454786e-01, -3.46187025e-04,
         1.05031413e-03,  6.56524273e-02,  9.20764058e-02,
        -1.07131909e-02,  2.55501615e-01,  3.05340233e-01,
         2.66452915e-01,  2.48845970e-01]])

In [ ]:
lr.intercept_

array([-3.53455399])

In [ ]:
result=1.07973614e-02*30+  3.53454786e-01*2+ -3.46187025e-04*70+1.05031413e-03*125+  6.56524273e-02*0+ 9.20764058e-02*1+-1.07131909e-02*65+  2.55501615e-01*0.2+  3.05340233e-01*1+.66452915e-01*0+ 2.48845970e-01*3+-3.53455399
print(result)

-1.8979699382